# mkdocs.yml
site_name: "hikari-arc documentation"
site_url: https://arc.hypergonial.com
repo_url: https://github.com/hypergonial/hikari-arc
copyright: Copyright &copy; 2023 hypergonial
edit_uri: edit/main/docs/
theme:
  name: material
  icon:
    logo: fontawesome/solid/book
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: octicons/sun-16
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: octicons/moon-24
        name: Switch to light mode
  features:
    - content.tabs.link
    - search.highlight
    - search.suggest
    - search.share
    - content.code.copy
    - content.code.select
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - navigation.footer
    - navigation.top
    - content.action.view
    - content.action.edit
    - content.tooltips
    - toc.follow

nav:
    - Home: index.md
    - Getting Started: getting_started.md
    - Tutorial:
        - tutorial/index.md
    - Guides:
        - guides/index.md
        - guides/interactions.md
        - guides/options.md
        - guides/command_groups.md
        - guides/context_menu.md
        - guides/hooks.md
        - guides/error_handling.md
        - guides/plugins_extensions.md
        - guides/dependency_injection.md
    - API Reference:
        - api_reference/index.md
        - api_reference/client.md
        - Command:
          - api_reference/command/index.md
          - api_reference/command/slash.md
          - api_reference/command/option.md
          - api_reference/command/message.md
          - api_reference/command/user.md
        - api_reference/context.md
        - api_reference/errors.md
        - api_reference/events.md
        - api_reference/plugin.md
        - Utils:
            - api_reference/utils/index.md
            - api_reference/utils/hooks.md
        - ABC:
            - api_reference/abc/index.md
            - api_reference/abc/client.md
            - api_reference/abc/command.md
            - api_reference/abc/option.md
            - api_reference/abc/plugin.md
            - api_reference/abc/hooks.md
            - api_reference/abc/error_handler.md
    - Changelog: changelog.md


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html

plugins:
  - autorefs
  - search
  - social
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          import:
            - https://docs.python.org/3.11/objects.inv
            - https://docs.hikari-py.dev/en/latest/objects.inv
            - https://alluka.cursed.solutions/objects.inv
          options:
            annotations_path: source
            docstring_section_style: spacy
            docstring_style: numpy
            inherited_members: true
            merge_init_into_class: true
            separate_signature: true
            show_signature_annotations: true
            show_source: false
            show_submodules: false
watch:
  - docs
  - README.md
  - arc
